### ISSUE TITLE
new things that are wrong

### ISSUE THREAD

**Issue by Purple906** [Purple906/jamming#1]
@mysterycommand 

can not read property 'id' of undefined. on line 60 of app.js 

I also left comments in the code regarding the things I think are probably wrong, but I tried. I included the command from the code academy tutorial, so you would have all the information I was given.
line 12 of SearchResults.js 
line 30 of Tracks.js

**Comment by mysterycommand** [comment]
So, this looks fine to me … a little sparse I guess since it's just the src directory and not a `package.json` or a `yarn.lock` like I might usually expect, but fine.

You don't need to re-pull this down to local since you already pushed this up from local? I mean you'll want to keep things in sync (`push`/`pull`), and I recommend working in branches, but there's no need to `git clone` this repo again.

Cannot read property 'x' of undefined always means that you should look for `something.x` and that something is undefined (where it should be an object with an x property like `{ x: 1 }` for example). On line 60 the culprit is `track` since track is an argument to that function and you're calling it without any arguments on line 77.

The `onAdd` stuff looks right to me except down in `Track.js` where you're checking if it `=== true` which it never should … `onAdd` should be a function, not a boolean. What you probably want is something like this:

```js
if (!this.props.isRemoval) {
  this.props.onAdd(this.props.track);
}
```

This brings the whole thing full circle since in `App.js` you're passing `addTrack` into the `onAdd` prop … so in `App.js` on line 77, instead of calling `this.state.addTrack()` it should just be `this.addTrack` (I also just noticed that you're referencing `this.state.addTrack` but it should just be `this.addTrack` since it's part of the component, not part of the component's state) … anyway, without parens will pass the function down without calling it until later.

Hopefully that all makes sense.
